### ISSUE TITLE
Add support for chemical plant and refinery

### ISSUE THREAD

**Issue by renoth** [renoth/factorio-factory-levels#19]

**Comment by renoth** [comment]
current master branch works ok but pipe connections get lost on levelup

**Comment by CaitSith2** [comment]
On that note, space exploration applies crafting category "melting" to chemical plant, so the leveled versions of these also need that category.

Also, while at it, might as well add in Electric Furnace and Centrifuge.

**Comment by JohnyDL** [comment]
Pump Jacks and Rocket Silos too?

**Comment by CaitSith2** [comment]
Pump jacks are unfortunately like the mining drills.  Since no stats are given on how many mining operations the machine has completed, there is no way to add support to them for those machines leveling up.  

It might be possible to support the rocket silo, although it only counts the total number of rockets made for its main crafting count,  so it won't level up fast.

**Comment by renoth** [comment]
Rocket silos launches could count towards global base produced items so that for example each rocket launch counts as produced item in all factories.

**Comment by JohnyDL** [comment]
That makes sense for miners and I'd suppose that doing it manually would have issues:

you can detect the ores under a miner when placed and current to calculate the amount of ore mined... but 2 miners can overlap the ores they mine, might be possible to do it for the patch as a collective whole though each miner being considered to have mined floor( (Start Ore - Current Ore) / miners on patch) but it might be horribly complicated. Would allow for the last few miners to get a super speed/prod boost, but for most cases it'd be fairly meaningless a more global thing like what Renoth said about silos might be more useful but I'd understand if it's not possible.

For the Silo the number of rockets could be x100 for the number of rocket parts produced... I don't know if it'd be better or worse for it to be Global vs the one building.

I figured since there are 9 vanilla buildings that can be beaconed, Miners, Furnaces, Assembers, Pump Jacks, Refineries, Chemical Plants, Centrifuges, Silos, Labs, it'd be worth completing the list of what could be considered... Labs would probably have to be global too and I kind of felt unnecessary to level up with more speed/prod given they can research that.
