### ISSUE TITLE
Crash (0.5.1)

### ISSUE THREAD

**Issue by NorXAengell** [renoth/factorio-factory-levels#21]
Crash occuring when i use a bluprint.
Can provide more information if needed.

Crashlog :

10801.982 Error MainLoop.cpp:1284: Exception at tick 54220810
Error while running event factory-levels::on_robot_built_entity (ID 14)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__factory-levels__/control.lua:209: in function 'upgrade_factory'
	__factory-levels__/control.lua:331: in function 'replace_built_entity'
	__factory-levels__/control.lua:339: in function <__factory-levels__/control.lua:336>

**Comment by NorXAengell** [comment]
The crash has occured with some ghost factory too

**Comment by renoth** [comment]
Hopefully i fixed the issue in 0.5.2

**Comment by Daryl-Lawton** [comment]
I'm getting a similar error of

Error while running event factory-levels::on_nth_tick(10)
LuaEntity API call when LuaEntity was invalid.
stack traceback:
	[C]: in function '__index'
	__factory-levels__/control.lua:209: in function 'upgrade_factory'
	__factory-levels__/control.lua:241: in function 'replace_machines'
	__factory-levels__/control.lua:285: in function <__factory-levels__/control.lua:253>

I don't really want to update to 0.5.2 since when I tried that all my chemical plants and oil refineries disappeared since you had to remove them to deal with the module bug

**Comment by renoth** [comment]
0.6.0 should fix the problem

**Comment by Daryl-Lawton** [comment]
I had a save before the crash and I just went right past it, so I can confirm that it is fixed. Thank you so much!
