### ISSUE TITLE
Causes non-recoverable errors on some level ups

### ISSUE THREAD

**Issue by KyriadosX** [renoth/factorio-factory-levels#56]
Attached crash message
Happens roughly three to five minutes after loading into a save

![image](https://github.com/user-attachments/assets/0a60a06d-8204-4022-ba7e-ce63ee92d71c)

**Comment by IG2WTC** [comment]
I noticed this as well.
First I thought this happens as soon as buildings get upgraded but that doesn't seem to be the case, since sometimes it manages to get Assembler 2s upgraded to 3s.
I can force this Error to happen, when changing the exponent. (With Mods as well as after removing all other mods, except DLC)

**Comment by renoth** [comment]
Duplicates #61
